name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
    branches: [main, develop]
  pull_request:
    paths:
      - 'backend/**'
    branches: [main, develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      RPC_URL_INFURA: ${{ secrets.RPC_URL_INFURA }}
      PK: ${{ secrets.PK }}

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Compile smart contracts (Hardhat)
        run: npx hardhat compile

      - name: Run unit tests
        run: npx hardhat test