name: Frontend

on:
  push:
    paths:
      - 'frontend/**'
    branches: [main, develop]
  pull_request:
    paths:
      - 'frontend/**'
    branches: [main, develop]

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint . --ext .ts,.tsx
        
      - name: Run build
        run: npm run build
